name: Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up dependencies
      run: |
        case ${{ matrix.os }} in
          ubuntu-latest)
            sudo apt-get update
            sudo apt-get install -y build-essential
            curl -LO https://github.com/raysan5/raylib/releases/download/5.0/raylib-5.0_linux_amd64.tar.gz
            tar -xvf raylib-5.0_linux_amd64.tar.gz
            mv raylib-5.0_linux_amd64 raylib
            ;;
          macos-latest)
            curl -LO https://github.com/raysan5/raylib/releases/download/5.0/raylib-5.0_macos.tar.gz
            tar -xvf raylib-5.0_macos.tar.gz
            mv raylib-5.0_macos raylib
            ;;
        esac
      shell: bash

    - name: Set up dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        curl -LO https://github.com/raysan5/raylib/releases/download/5.0/raylib-5.0_win64_mingw-w64.zip
        Expand-Archive -Path raylib-5.0_win64_mingw-w64.zip -DestinationPath raylib
      shell: powershell

    - name: Install Zig
      run: |
        case ${{ matrix.os }} in
          ubuntu-latest)
            curl -LO https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz
            tar -xvf zig-linux-x86_64-0.13.0.tar.xz
            echo "ZIG_PATH=$(pwd)/zig-linux-x86_64-0.13.0" >> $GITHUB_ENV
            ;;
          macos-latest)
            curl -LO https://ziglang.org/download/0.13.0/zig-macos-x86_64-0.13.0.tar.xz
            tar -xvf zig-macos-x86_64-0.13.0.tar.xz
            echo "ZIG_PATH=$(pwd)/zig-macos-x86_64-0.13.0" >> $GITHUB_ENV
            ;;
        esac
      shell: bash

    - name: Install Zig (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        curl -LO https://ziglang.org/download/0.13.0/zig-windows-x86_64-0.13.0.zip
        Expand-Archive -Path zig-windows-x86_64-0.13.0.zip -DestinationPath zig
        echo "ZIG_PATH=$(pwd)/zig/zig-windows-x86_64-0.13.0" >> $env:GITHUB_ENV
      shell: powershell

    - name: Add Zig to PATH
      run: |
        echo "$ZIG_PATH" | sudo tee -a $GITHUB_PATH

    - name: Verify Zig Installation
      run: |
        echo "Zig path: $ZIG_PATH"
        ls -l $ZIG_PATH
        $ZIG_PATH/zig version

    - name: Build for ${{ matrix.os }}
      run: |
        echo "Building with Zig at path: $ZIG_PATH"
        $ZIG_PATH/zig build -Dtarget=${{ matrix.os == 'windows-latest' && 'x86_64-windows-gnu' || matrix.os == 'macos-latest' && 'x86_64-macos' || 'x86_64-linux-gnu' }} -Doptimize=ReleaseSafe
        echo "Build completed"
      timeout-minutes: 60
